annuaire-entreprises-data-gouv-fr/search-infra

utils.py
related to https://github.com/etalab/data-engineering-stack/pull/14
closes #13
=> Add error handling to getting AIO color function

DAG-insert-elk-sirene.py, utils.py
depended on by https://github.com/etalab/annuaire-entreprises-search-api/pull/37
depends on https://github.com/etalab/data-engineering-stack/pull/16
related to https://github.com/etalab/annuaire-entreprises-search-api/issues/36
=> Add get color and check elastic tasks to workflow

DAG-insert-elk-sirene.py, utils.py
closes #22 
depends on https://github.com/etalab/data-engineering-stack/pull/17
=> Use airflow vars for env vars instead of .env files

DAG-insert-elk-sirene.py
=> Add email notification for failure

DAG-insert-elk-sirene.py
=> Restart aio container at the end of preprocessing workflow

DAG-insert-elk-sirene.py
=> Add email alert for airflow success

process-data-before-indexation.ipynb
closes #34 
closes #36 
depends on https://github.com/etalab/data-engineering-stack/pull/22
=> Add international info to address

elasticsearch/process_unites_legales.py
=> Replace missing nombre_etablissements_ouverts with zero

DAG-insert-elk-sirene.py, task_functions.py
=> Add sitemap

task_functions.py
=> feat: add identifiant association

data_aggregation/collectivite_territoriale.py, data_aggregation/update_elasticsearch.py, elasticsearch/mapping_sirene_index.py
=> Ajouter liste des élus à l'index

elasticsearch/process_unites_legales.py, helpers/utils.py, task_functions.py
=> Fix données manquantes entrepreneurs spectacle sur l'index

task_functions.py
Revert https://github.com/etalab/annuaire-entreprises-search-infra/pull/99
=> fix: decrease docs unindexed's limit required to fail check elastic task

DAG-insert-elk-sirene.py
Revert https://github.com/etalab/annuaire-entreprises-search-infra/pull/101
=> Activate aio build

DAG-change-api-color.py
closes https://github.com/etalab/annuaire-entreprises-search-infra/issues/96
In case of an issue with index in production, dag allows to quickly change colours and switch to functional index.
=> Dag to change colour and execute API container 

data_enrichment.py, elasticsearch/mapping_sirene_index.py, elasticsearch/process_unites_legales.py
related to https://github.com/etalab/annuaire-entreprises-search-api/issues/172
Change `nature_juridique_unite_legale` mapping to keyword in order to use a prefix query to filter on it.
=> feat: index nature juridique as keyword

.pre-commit-config.yaml, DAG-flush-and-execute-queries.py, DAG-flush-cache-only.py, DAG-flush-cache.py, task_functions.py
I will add this task to the main DAG once tested in production env.
=> Add cache flushing DAG

.pre-commit-config.yaml, data_enrichment.py, elasticsearch/mapping_sirene_index.py, elasticsearch/process_unites_legales.py, sqlite/queries/select_sitemap_fields.py, task_functions/create_sitemap.py
related to[ #188](https://github.com/etalab/annuaire-entreprises-search-api/issues/188)
- ajout slug dans elasticsearch
- refacto fonction génération slug pour le sitemap
=> Ajout slug dans elasticsearch

elasticsearch/process_unites_legales.py, task_functions/create_sitemap.py
=> Fix slug functions

data_preprocessing/uai.py
feat: update uai source to get menj, mensr, onisep data together
=> Mise à jour source de données UAI

DAG-insert-elk-sirene.py, elasticsearch/mapping_sirene_index.py, elasticsearch/process_unites_legales.py, helpers/es_fields.py, sqlite/queries/select_fields_to_index.py, task_functions/create_additional_data_tables.py
=> Ajout données egapro

data_preprocessing/etablissements.py, sqlite/queries/replace_table_siret_siege.py
est_siege is `true` in Stock and `True` in flux. Harmonize
=> same format that stock file

DAG-insert-elk-sirene.py
=> feat: add flush cache task to main workflow

DAG-insert-elk-sirene.py, tests/e2e_tests/run_tests.py, tests/e2e_tests/test_api.py
=> Add API E2E tests to Airflow Workflow

task_functions/slow_requests.py
The website calls the search API with additional parameters . This PR adds the full request to the list of slow queries to execute after flushing the cache.
closes #121
=> feat: add slow queries with annuaire full requests

DAG-insert-elk-sirene.py
=> feat: schedule workflow every monday, wednesday and friday at midnight

data_preprocessing/agence_bio.py, elasticsearch/mapping_sirene_index.py, elasticsearch/process_unites_legales.py, sqlite/queries/select_fields_to_index.py
=> Remove `statut_bio` field and use only siren with label `ENGAGEE`  

data_preprocessing/entrepreneur_spectacle.py
=> fix: keep the latest spectacle statut

data_enrichment.py, helpers/utils.py, task_functions/create_etablissements_tables.py, task_functions/create_unite_legale_tables.py
=> chore: change logging level from info to debug to avoid too many logs

elasticsearch/mapping_sirene_index.py, helpers/clean_dirigeants.py
=> feat: strip apostrophes and other special char in mapping analyser

data_enrichment.py, elasticsearch/process_unites_legales.py
=> feat: use only `commune`  in address for non diffusible

elasticsearch/mapping_sirene_index.py
related to https://github.com/etalab/annuaire-entreprises-search-api/issues/235
=> feat: change categorie_entreprise mapping from text to keyword

data_enrichment.py, elasticsearch/process_unites_legales.py, task_functions/create_sitemap.py
=> Utiliser le siren uniquement pour le slug des `non-diffusibles`

helpers/utils.py
Use `False` as default value for `est_qualiopi` when a value is not given.
=> fix: return False if sqlite bool is zero

data_preprocessing/unite_legale.py, elasticsearch/mapping_sirene_index.py, helpers/utils.py, sqlite/queries/create_table_flux_unite_legale.py, sqlite/queries/create_table_unite_legale.py, sqlite/queries/replace_table_unite_legale.py, sqlite/queries/select_fields_to_index.py
=> Ajouter la données de `societe_entreprise_mission`

data_preprocessing/collectivite_territoriale.py
Main workflow fails because the `elus` files have been changed in data.gouv. Mainly columns names.
=> fix: update elu preprocessing dataset fields

data_preprocessing/unite_legale.py, elasticsearch/mapping_sirene_index.py, sqlite/queries/create_table_flux_unite_legale.py, sqlite/queries/create_table_unite_legale.py, sqlite/queries/replace_table_unite_legale.py, sqlite/queries/select_fields_to_index.py
depends on https://github.com/etalab/datagouvfr_data_pipelines/pull/25
closes #170
=> [DATA] Ajouter `annee_categorie_entreprise` et `annee_tranche_effectif_salarie` à l'index

data_preprocessing/bilan_financier.py, elasticsearch/mapping_sirene_index.py, sqlite/queries/create_table_bilan_financier.py, sqlite/queries/select_fields_to_index.py
closes #176 
depends on https://github.com/etalab/datagouvfr_data_pipelines/pull/51
=> Intégrer les types de bilans dans les données financières + màj des données 

DAG-clean-logs.py
Airflow indexing logs can be pretty hefty.
This daily dag will clean any and all log files and directories older than 15 days.
=> feat: add dag to delete logs older than 15 days

tests/e2e_tests/test_api.py
=> feat: add new e2e test to test api task

data_pipelines/config.py, data_pipelines/rne/stock/DAG.py, data_pipelines/rne/stock/README.md, data_pipelines/rne/stock/get_stock.sh, data_pipelines/rne/stock/task_functions.py, data_pipelines/utils/mattermost.py, data_pipelines/utils/minio_functions.py
* **Stock DAG** : fetches a zip file from the INPI website, processes the JSON files within it, and saves them to a MinIO instance. These files will subsequently be used to generate the stock files required for dirigeants data in Annuaire des Entreprises.
=> [data_pipelines][rne]Download RNE stock files and upload them to MINIO

config.py, data_pipelines/metadata/cc/task_functions.py
The URL for the Dares CC Excel file changes every month, requiring the download URL to be updated accordingly.
=> [METADATA]fix: use dynamic url to download dares cc file

workflows/data_pipelines/elasticsearch/task_functions/sitemap.py
The sitemap path should also be changed on the website.
Awaiting the transition, I have left sitemaps in both paths (old/updated).
cc @XavierJp
=> [INDEXING]chore: move sitemap to appropriate env directory in MinIO

workflows/data_pipelines/elasticsearch/mapping_index.py, workflows/data_pipelines/elasticsearch/sqlite/fields_to_index.py, workflows/data_pipelines/etl/data_fetch_clean/etablissements.py, workflows/data_pipelines/etl/sqlite/queries/etablissements.py, workflows/data_pipelines/sirene/flux/task_functions.py
related to https://github.com/etalab/annuaire-entreprises-site/issues/842
=> [DATA-PIPELINES] Add `statut_diffusion_etablissement` to index

workflows/data_pipelines/rne/database/process_rne.py, workflows/data_pipelines/rne/database/task_functions.py
This PR addresses a critical issue within the processing DAG of the RNE database. The problem arises when encountering incorrectly encoded JSON lines in RNE flux files, causing the DAG to fail.
To resolve this issue effectively, the following steps have been implemented:
1. Implementation of a mechanism to bypass problematic lines encountered during processing. These lines are skipped, and the encountered issue is appropriately logged in Airflow for further investigation.
2. Modification to the workflow to exclude processing of the last RNE flux file. This precautionary measure mitigates the risk of processing incomplete files that might otherwise pass without error due to the implemented line skipping mechanism. This adjustment ensures that files are only processed once they are …
=> [DATA-PIPELINES][RNE]Fortify RNE database processing from flux files

workflows/data_pipelines/elasticsearch/data_enrichment.py, workflows/data_pipelines/elasticsearch/mapping_index.py, workflows/data_pipelines/elasticsearch/process_unites_legales.py
related to https://github.com/etalab/annuaire-entreprises-search-api/issues/340
The purpose of this PR is to add an integer code which represents `catagorie entreprise` to index.
=> [INDEXING]Add integer code to represent `categorie entreprise`

workflows/data_pipelines/elasticsearch/DAG_index_data.py
AIO container execution task was not included in new archi. This PR adds task to main DAG.
=> [INDEXING][API]fix: build AIO container in indexing dag if dev env

config.py, helpers/utils.py, workflows/data_pipelines/bilans_financiers/DAG.py, workflows/data_pipelines/bilans_financiers/README.md, workflows/data_pipelines/bilans_financiers/task_functions.py
related to https://github.com/etalab/annuaire-entreprises-search-infra/issues/291
=> [DATA-PIPELINES]Add dag to preprocess `Bilans Financiers` data

helpers/utils.py, workflows/data_pipelines/etl/data_fetch_clean/dirigeants.py, workflows/data_pipelines/rne/database/map_rne.py, workflows/data_pipelines/rne/database/rne_model.py
=> [FIX]Add missing role for dirigeants personnes morales

workflows/data_pipelines/agence_bio/DAG.py, workflows/data_pipelines/agence_bio/task_functions.py, workflows/data_pipelines/bilans_financiers/DAG.py, workflows/data_pipelines/bilans_financiers/task_functions.py, workflows/data_pipelines/marche_inclusion/DAG.py, workflows/data_pipelines/rne/database/task_functions.py
Send email notifications in case of preprocessing failure in new DAGs. Also fix emoji in Tchap notifications.
=> [DATA-PIPELINES]chore: add failure notifications to new DAGs

workflows/data_pipelines/etl/sqlite/queries/etablissements.py
Bug in `statut_diffusion_etablissement` field value.
=> [DATA-PIPELINES][RNE]fix: change field order in sqlite rne siege query

helpers/minio_helpers.py, workflows/data_pipelines/elasticsearch/task_functions/fetch_db.py, workflows/data_pipelines/etl/DAG_extract_transform_load.py, workflows/data_pipelines/etl/task_functions/create_dirigeants_tables.py, workflows/data_pipelines/etl/task_functions/upload_db.py, workflows/data_pipelines/rne/database/DAG.py, workflows/data_pipelines/rne/database/task_functions.py, workflows/data_pipelines/rne/flux/flux_tasks.py
To optimise storage on MinIO and enhance processing speed this PR compresses files before uploading to MinIo.
=> [CHORE]Compress RNE json files and database files

workflows/data_pipelines/rne/database/task_functions.py
=> [DATA-PIPELINES][BUG]fix: database rne source file

workflows/data_pipelines/elasticsearch/data_enrichment.py, workflows/data_pipelines/elasticsearch/process_unites_legales.py
closes https://github.com/etalab/annuaire-entreprises-search-api/issues/353
=> [LABELS]feat: label service public from insee only

workflows/data_pipelines/elasticsearch/data_enrichment.py, workflows/data_pipelines/elasticsearch/process_unites_legales.py
related to https://github.com/etalab/annuaire-entreprises-site/issues/1024
=> [DATA-PIPELINES][LABELS]feat: update `service public` definition

tests/e2e_tests/test_api.py, workflows/data_pipelines/agence_bio/task_functions.py, workflows/data_pipelines/colter/task_functions.py, workflows/data_pipelines/convcollective/task_functions.py, workflows/data_pipelines/egapro/task_functions.py, workflows/data_pipelines/ess_france/task_functions.py, workflows/data_pipelines/finess/task_functions.py, workflows/data_pipelines/formation/task_functions.py, workflows/data_pipelines/rge/task_functions.py, workflows/data_pipelines/rne/database/task_functions.py, workflows/data_pipelines/rne/flux/flux_tasks.py, workflows/data_pipelines/rne/stock/task_functions.py, workflows/data_pipelines/sirene/etab/task_functions.py, workflows/data_pipelines/sirene/flux/task_functions.py, workflows/data_pipelines/sirene/ul/task_functions.py, workflows/data_pipelines/spectacle/task_functions.py, workflows/data_pipelines/uai/task_functions.py
* Fix typo in e2e test
* Update workflow notifications
=> [CHORE]Miscellaneous

workflows/data_pipelines/rne/database/process_rne.py
=> [BUG][DATA-PIPELINES][RNE]fix: remove all previous mentions of siren in `dirigeants` tables even if new siren entry has no `dirigeants`

workflows/data_pipelines/rne/database/map_rne.py, workflows/data_pipelines/rne/database/process_rne.py, workflows/data_pipelines/rne/database/rne_model.py, workflows/data_pipelines/rne/database/task_functions.py, workflows/data_pipelines/rne/database/ul_model.py
closes #https://github.com/annuaire-entreprises-data-gouv-fr/search-infra/issues/249
=> [DATA-PIPELINES][RNE]feat: extract immatriculation object from RNE data

helpers/sqlite_client.py, workflows/data_pipelines/elasticsearch/mapping_index.py, workflows/data_pipelines/elasticsearch/process_unites_legales.py, workflows/data_pipelines/elasticsearch/sqlite/fields_to_index.py, workflows/data_pipelines/etl/DAG_extract_transform_load.py, workflows/data_pipelines/etl/task_functions/create_etablissements_tables.py, workflows/data_pipelines/etl/task_functions/create_immatriculation_table.py, workflows/data_pipelines/etl/task_functions/create_unite_legale_tables.py
depends on https://github.com/annuaire-entreprises-data-gouv-fr/search-infra/pull/329
=> [INDEX][RNE][IMMATRICULATION]Add immatriculation object to Elasticsearch index

workflows/data_pipelines/rne/database/rne_model.py
File from `18/06` has weirdly formatted immatriculation date.
=> [RNE][IMMATRICULATION]fix: use str type, to extract date immat field from files, instead of date type

workflows/data_pipelines/rne/database/map_rne.py, workflows/data_pipelines/rne/database/rne_model.py
=> [DATA-PIPELINES][RNE][IMMATRICULATION]Use `indicateur principal` to determine nature entreprise list

workflows/data_pipelines/rne/database/map_rne.py, workflows/data_pipelines/rne/database/process_rne.py, workflows/data_pipelines/rne/database/rne_model.py, workflows/data_pipelines/rne/database/task_functions.py, workflows/data_pipelines/rne/database/ul_model.py
=> [DATA-PIPELINES][RNE]Add `beneficiaires effectifs` to RNE database

workflows/data_pipelines/elasticsearch/clean_data.py, workflows/data_pipelines/elasticsearch/data_enrichment.py, workflows/data_pipelines/elasticsearch/mapping_index.py, workflows/data_pipelines/elasticsearch/process_unites_legales.py, workflows/data_pipelines/elasticsearch/sqlite/fields_to_index.py, workflows/data_pipelines/etl/DAG_extract_transform_load.py, workflows/data_pipelines/etl/data_fetch_clean/dirigeants.py, workflows/data_pipelines/etl/sqlite/queries/beneficiaires.py, workflows/data_pipelines/etl/task_functions/create_dirig_benef_tables.py
=> [INDEX][BENEFICIAIRES]Add beneficiaires effectifs to ES index

workflows/data_pipelines/etl/data_fetch_clean/dirigeants.py, workflows/data_pipelines/etl/sqlite/queries/dirigeants.py
closes https://github.com/annuaire-entreprises-data-gouv-fr/search-api/issues/352
=> [FIX]Include dirigeants pm that are missing a siren number

helpers/api_client.py, helpers/utils.py, workflows/data_pipelines/agence_bio/bio_client.py, workflows/data_pipelines/agence_bio/task_functions.py, workflows/data_pipelines/sirene/flux/insee_client.py
This PR introduces a new `fetch_all` method to the `APIClient` class, enabling efficient retrieval of paginated data from API endpoints. This addition significantly enhances the client's capabilities for handling large datasets that span multiple pages.
This method is used to refactor the INSEEAPIClient as well as BIOAPIClient.
=> [REFACTOR]Bio API and Insee API calls

helpers/sqlite_client.py, workflows/data_pipelines/etl/DAG_extract_transform_load.py, workflows/data_pipelines/etl/data_fetch_clean/unite_legale.py, workflows/data_pipelines/etl/sqlite/queries/unite_legale.py, workflows/data_pipelines/etl/task_functions/create_etablissements_tables.py, workflows/data_pipelines/etl/task_functions/create_unite_legale_tables.py, workflows/data_pipelines/sirene/flux/task_functions.py
related to https://github.com/annuaire-entreprises-data-gouv-fr/search-infra/issues/271
=> [NEW-DATA][INSEE]Add `ancien siege` table to database

workflows/data_pipelines/elasticsearch/data_enrichment.py, workflows/data_pipelines/elasticsearch/mapping_index.py, workflows/data_pipelines/elasticsearch/sqlite/fields_to_index.py
related to https://github.com/annuaire-entreprises-data-gouv-fr/search-infra/issues/271 
depends on https://github.com/annuaire-entreprises-data-gouv-fr/search-infra/pull/366
=> [ELASTICSEARCH]Index anciens sieges

workflows/data_pipelines/elasticsearch/data_enrichment.py, workflows/data_pipelines/elasticsearch/process_unites_legales.py
related to https://github.com/annuaire-entreprises-data-gouv-fr/site/issues/1163
=> [SLUG]Add `nom commercial`(siege) to slug

workflows/data_pipelines/elasticsearch/indexing_unite_legale.py
In the development environment, the indexing workflow has been failing because the task that checks the number of documents is returning zero. We believe this might be due to the index not being refreshed before the request to retrieve the document count. 
This PR implements a mechanism that retries fetching the document count, a few times, if zero is returned initially.
=> [INDEX]Add retry mechanism if number of docs indexed returned is zero

workflows/data_pipelines/elasticsearch/data_enrichment.py
related to https://github.com/annuaire-entreprises-data-gouv-fr/search-api/pull/422
related to https://github.com/annuaire-entreprises-data-gouv-fr/site/issues/1228
=> [BUG]fix(slug): only use denomination usuelle in case the value is valid

config.py, workflows/data_pipelines/sirene/flux/insee_client.py
related to https://github.com/annuaire-entreprises-data-gouv-fr/site/issues/1254
=> [DATA-PIPELINES][INSEE]Update Insee API url and authentification

workflows/data_pipelines/rne/flux/rne_api.py
Lower page size in case of `Error: Allowed memory`.
=> [RNE]fix: lower page size in case of a 500

workflows/data_pipelines/rne/flux/rne_api.py
=> [RNE]fix: lower page size in case of 500 related to memory

workflows/data_pipelines/rne/flux/rne_api.py
=> [RNE]fix: lower page size in case of 500 error code

workflows/data_pipelines/elasticsearch/data_enrichment.py
related to #400 
Detect all SIREN numbers with this bug.
=> [TMP][SIRENE]chore: log siren where nom commercial is suppression du nom commercial

workflows/data_pipelines/uai/DAG.py, workflows/data_pipelines/uai/task_functions.py
They changed the column names. Again.
=> [DATA-PIPELINES][UAI]Update column names and send failure notifications

.gitignore, .pre-commit-config.yaml, config.py, helpers/__init__.py, helpers/notification.py, helpers/tchap.py, workflows/data_pipelines/metadata/cc/DAG-get-metadata-cc.py, workflows/data_pipelines/metadata/cc/task_functions.py
Related to https://github.com/annuaire-entreprises-data-gouv-fr/search-infra/issues/418
=> [REFACTOR] Improve Convention Collective notification

workflows/data_pipelines/etl/data_fetch_clean/organisme_formation.py
=> [BUG][FORMATION Use minio url in ETL

helpers/utils.py, tests/e2e_tests/test_api.py, workflows/data_pipelines/metadata/cc/README.md, workflows/data_pipelines/metadata/cc/dag.py, workflows/data_pipelines/metadata/cc/task_functions.py
Related to https://github.com/annuaire-entreprises-data-gouv-fr/search-infra/issues/476
- Fallback on previous months folders in case the file was uploaded to the wrong folder
- Add accents to months names
- Add README.md
- Also added a `ShortCircuitOperator` to increase the frequency of DAG runs but avoid running tasks if the metadata was already updated.
=> [BUG][GET_METADATA_CC] Fix url

workflows/data_pipelines/rne/database/map_rne.py, workflows/data_pipelines/rne/database/process_rne.py, workflows/data_pipelines/rne/database/rne_model.py, workflows/data_pipelines/rne/database/ul_model.py
related to https://github.com/annuaire-entreprises-data-gouv-fr/search-infra/issues/479
related to https://github.com/annuaire-entreprises-data-gouv-fr/search-infra/issues/364
=> [NEW DATA][RNE]Add `etablissement` and `activite` data to rne db

workflows/data_pipelines/uai/processor.py
Issue caused by a git conflict resolution gone wrong.
=> [BUG][UAI] Notification push

.gitignore, workflows/data_pipelines/sirene/flux/processor.py
To fix notifications as 0 even though they are should not :
=> [BUG][SIRENE.FLUX] Fix notification count

.github/workflows/linting.yml, .pre-commit-config.yaml, workflows/data_pipelines/data_gouv/processor.py
Related to https://github.com/annuaire-entreprises-data-gouv-fr/site/pull/1634
+ remove black from pre-commit
black is complaining about files not concerned by this PR
ruff being more efficient and smarter for the same results, removing black nowaday makes sense imo
=> [PUBLISH_DATAGOUV] Add orga consulaire to L103 list

workflows/data_pipelines/etl/dag.py, workflows/data_pipelines/sirene/flux/dag.py
depends on https://github.com/annuaire-entreprises-data-gouv-fr/data-engineering-stack/pull/30
=> chore: run sirene+etl pipelines earlier in the day

helpers/data_processor.py, helpers/filesystem.py, helpers/minio_helpers.py, workflows/data_pipelines/data_gouv/processor.py, workflows/data_pipelines/elasticsearch/task_functions/fetch_db.py, workflows/data_pipelines/elasticsearch/task_functions/sitemap.py, workflows/data_pipelines/elasticsearch/task_functions/snapshot.py, workflows/data_pipelines/elasticsearch/task_functions/source_updates.py, workflows/data_pipelines/etl/data_fetch_clean/etablissements.py, workflows/data_pipelines/etl/data_fetch_clean/unite_legale.py, workflows/data_pipelines/etl/task_functions/create_dirig_benef_tables.py, workflows/data_pipelines/etl/task_functions/create_json_last_modified.py, workflows/data_pipelines/etl/task_functions/upload_db.py, workflows/data_pipelines/metadata/cc/task_functions.py, workflows/data_pipelines/rne/database/task_functions.py, workflows/data_pipelines/rne/flux/flux_tasks.py, workflows/data_pipelines/rne/maintenance/task_functions.py, workflows/maintenance/DAG_clean_minio.py
Everytime Airflow parse the Python files it currently executes some MinIO code. It happens several times per minute. Those changes will prevent this.
Tested on dev_01 ✅
=> Stop minio connecting during parsing

tests/e2e_tests/test_api.py, workflows/data_pipelines/achats_responsables/README.md, workflows/data_pipelines/achats_responsables/config.py, workflows/data_pipelines/achats_responsables/dag.py, workflows/data_pipelines/achats_responsables/processor.py, workflows/data_pipelines/data_gouv/processor.py, workflows/data_pipelines/data_gouv/queries.py, workflows/data_pipelines/elasticsearch/mapping_index.py, workflows/data_pipelines/elasticsearch/process_unites_legales.py, workflows/data_pipelines/elasticsearch/sqlite/fields_to_index.py, workflows/data_pipelines/etl/dag.py, workflows/data_pipelines/etl/task_functions/create_json_last_modified.py
Related to https://github.com/annuaire-entreprises-data-gouv-fr/search-infra/issues/495
Requires to be tested:
=> [NEW_DATA] Add label achats responsables to the index

workflows/data_pipelines/data_gouv/processor.py, workflows/data_pipelines/elasticsearch/mapping_index.py, workflows/data_pipelines/elasticsearch/process_unites_legales.py, workflows/data_pipelines/elasticsearch/sqlite/fields_to_index.py, workflows/data_pipelines/etl/dag.py, workflows/data_pipelines/etl/task_functions/create_json_last_modified.py, workflows/data_pipelines/patrimoine_vivant/README.md, workflows/data_pipelines/patrimoine_vivant/config.py, workflows/data_pipelines/patrimoine_vivant/dag.py, workflows/data_pipelines/patrimoine_vivant/processor.py
related to https://github.com/annuaire-entreprises-data-gouv-fr/search-api/issues/477
https://www.data.gouv.fr/fr/datasets/entreprises-du-patrimoine-vivant-epv/
=> [NEW-DATA]Index Patrimoine Vivant data

workflows/data_pipelines/data_gouv/queries.py
=> [BUG][PUBLISH_TO_DATAGOUV] est_patrimoine_vivant

helpers/data_processor.py, helpers/datagouv.py, helpers/utils.py, workflows/data_pipelines/colter/README.md, workflows/data_pipelines/colter/config.py, workflows/data_pipelines/colter/dag.py, workflows/data_pipelines/colter/processor.py
Replace missing [EPCI and communes datasets](https://www.data.gouv.fr/fr/datasets/630f5173873064dd369479b4/#/resources/42b16d68-958e-4518-8551-93e095fe8fda) by a [new one for EPCI](https://www.data.gouv.fr/fr/datasets/630f5173873064dd369479b4/) and also a new one for [communes](https://www.data.gouv.fr/fr/datasets/630f5173873064dd369479b4/#/resources/1e3493b3-7fc0-4005-8aa7-240bdf17e617).
The logic has also been slightly updated to better handle special cases.
=> [COLTER] Replace banatic dataset

helpers/minio_helpers.py, workflows/data_pipelines/achats_responsables/dag.py, workflows/data_pipelines/agence_bio/dag.py, workflows/data_pipelines/bilans_financiers/dag.py, workflows/data_pipelines/colter/dag.py, workflows/data_pipelines/convcollective/dag.py, workflows/data_pipelines/data_gouv/dag.py, workflows/data_pipelines/egapro/dag.py, workflows/data_pipelines/elasticsearch/DAG_index_data.py, workflows/data_pipelines/elasticsearch/DAG_rollback.py, workflows/data_pipelines/elasticsearch/DAG_snapshot_data.py, workflows/data_pipelines/ess_france/dag.py, workflows/data_pipelines/etl/dag.py, workflows/data_pipelines/finess/dag.py, workflows/data_pipelines/formation/dag.py, workflows/data_pipelines/marche_inclusion/dag.py, workflows/data_pipelines/metadata/cc/dag.py, workflows/data_pipelines/patrimoine_vivant/dag.py, workflows/data_pipelines/rge/dag.py, workflows/data_pipelines/rne/database/DAG.py, workflows/data_pipelines/rne/flux/DAG.py, workflows/data_pipelines/rne/stock/DAG.py, workflows/data_pipelines/sirene/stock/dag.py, workflows/data_pipelines/spectacle/dag.py, workflows/data_pipelines/uai/dag.py, workflows/maintenance/DAG_clean_logs_and_runs.py, workflows/maintenance/DAG_clean_minio.py, workflows/maintenance/DAG_flush_and_execute_queries.py, workflows/maintenance/DAG_flush_cache_only.py
* Use `schedule` instead of the deprecated `schedule_interval`
* And solve a warning on a wrong use of backslash in docstring
=> [REFACTOR] Prepare for airflow3

workflows/data_pipelines/marche_inclusion/dag.py
Have currently trouble running during the night
=> [BUG][marche_inclusion] Change schedule

workflows/data_pipelines/etl/task_functions/create_etablissements_tables.py, workflows/data_pipelines/etl/task_functions/create_unite_legale_tables.py
We prefer the data to not be updated than to release a corrupted index.
=> [ETL] Make etl dag fail for any task failure

workflows/data_pipelines/agence_bio/api.py
=> [BUG]fix: increase api bio batch size

workflows/data_pipelines/rne/database/map_rne.py, workflows/data_pipelines/rne/database/rne_model.py
Not very clean but the upcoming RNE RNE will clean everything!
=> [RNE]fix: use roleEntreprise and not role for dirigeant pp
