task_functions.py

To temporarily resolve staging fail due to nginx body memory limit.

feat: increase limit of docs unindexed required to fail check elastic task

---

DAG-insert-elk-sirene.py

related to https://github.com/etalab/annuaire-entreprises-search-api/issues/135
To insure minimal downtime in production because of the breaking changes related to new data addition (établissements), the workflow will skip the API build this time.

Skip AIO API container build in airflow DAG

---

DAG-insert-elk-sirene.py

Staging timeout after 8 hours. Increase timeout to 12 hours.

perf: increase DAG timeout to 12 hours

---

elasticsearch/indexing_unite_legale.py
labels/departements.py

related to https://github.com/etalab/annuaire-entreprises-search-api/issues/148
Searching in Elasticsearch is very slow when big documents are concerned (e.g `la poste`). To better the performance, we separate the larger documents (mora than a 100 établissements) into smaller ones, then collapse them suing `siren` number in the API front.

Break big documents into smaller ones

---

data_enrichment.py
elasticsearch/mapping_sirene_index.py

closes #106
Changing the mapping for the code fields to be able to use multi-match to search them (`cross fields` in `multi-match` requires all fields to use the same analyser).

Utiliser le `code postal` dans l'adresse à la place du `code commune`

---

.github/workflows/linting.yml
.pre-commit-config.yaml
data_preprocessing/uai.py
elasticsearch/create_sirene_index.py

Use pre-commit hooks for linting.
Update workflow actions (v3) and replace super-linter with `ruff` and `black` linters.
closes #108

Update CI linting & add pre-commit hooks

---

DAG-insert-elk-sirene.py
data_preprocessing/bilan_financier.py
elasticsearch/mapping_sirene_index.py
elasticsearch/process_unites_legales.py
sqlite/queries/create_table_bilan_financier.py
sqlite/queries/select_fields_to_index.py
task_functions/create_additional_data_tables.py

- bilan_financier object
containing three properties : 
- ca # chiffre d'affaire
- resultat_net # résultat net
- date_cloture_exercice # date de cloture de l'exercice
I choose to only put latest `bilan` data in the index (where `date_cloture_exercice` is the highest) instead of putting an array of all `bilan_financier` from a company. It is simplier to read and to query. 
If we have a specific need on multiple `bilan_financier` for one company in API, we will evolve this format.

Add bilan_financier object to elasticsearch

---

data_preprocessing/organisme_formation.py
helpers/utils.py

Get `qualiopi` updated data from DGE website and remove siret without valid certifications.
closes #150 
closes #149 
related to https://github.com/etalab/annuaire-entreprises-search-api/issues/227

feat: update qualiopi source and keep valid certifications only

---

data_enrichment.py

Use the three first digits of deposit when `dep=98` instead of the two first digits.

fix: use 3 first digits for dep when dep is 98

---

DAG-insert-elk-sirene.py
DAG-restart-api.py

Add a 60 seconds timeout to avoid timeouts on dev server.

Add command timeout to DAGs using SSHOperator

---

DAG-insert-elk-sirene.py
data_preprocessing/etablissements.py
data_preprocessing/unite_legale.py

The data flux does not yet exist in `Minio` in the first of every month so the workflow fails.

Use `flux` data from previous month if first day of the month

---

DAG-insert-elk-sirene.py

Add params to DAG to ignore past runs (schedule in case of Airflow reset) and limit number of active runs to 1 only.

feat: limit parallel runs

---

data_preprocessing/organisme_formation.py

When both `est_qualiopi=True` and `est_qualiopi=False` exist for one siren. The row used by Sqlite is uknown.
This PR removes `False` values in table when `True` values exist.

fix: remove false est_qualiopi values when true values exist

---

DAG-clean-logs.py

Clean Airflow logs every Monday night instead of daily because it might interfere with ongoing runs and schedules.

feat: clean logs every monday instead of daily

---

DAG-clean-logs.py

For scheduled runs to run automatically, a specific start date has to be given to DAG.

fix: add specific start date otherwise it doesn't run even with schedule

---

.github/workflows/linting.yml

GitHub Actions raises error when linting due to `ruff` update.

CI: update ruff format option

---

elasticsearch/data_enrichment.py
elasticsearch/mapping_index.py
elasticsearch/process_unites_legales.py

Use `nature juridique` as well as `identifiant association` fields to label associations.

feat: add `est_association` field to ES

---

data_pipelines/config.py

Env variable is called `ENV` in .env file and not `AIRFLOW_ENV`, so `staging` and `production` use the default value `dev` for RNE workflows.

fix: update airflow env var

---

data_preprocessing/convention_collective.py

[`Liste convention collective par établissement`](https://www.data.gouv.fr/fr/datasets/liste-des-conventions-collectives-par-entreprise-siret/#/resources)  changed their file, this somehow caused the stable data.gouv link to change which in turn caused the indexation workflow to fail. This PR updates the URL.

fix: update datagouv stable url to download convention collective csv

---

data_pipelines/rne/flux/DAG.py

The workflow consistently encounters issues. I'm attempting to run it at 2 am, aiming for a time when the RNE API hopefully experiences the least activity.

[data-pipelines][rne]feat: execute flux rne dag daily at 2am

---

data_pipelines/rne/flux/flux_tasks.py
utils/minio_helpers.py

Given the unreliable nature of the RNE API, it's crucial to enhance the robustness of our workflow to ensure we capture as much data as possible. Specifically, the goal is to persist all data received from the API, even if it's incomplete for a particular day.
In response to this, this PR introduces a mechanism to save JSON files, even if they are unfinished, into MinIO in the event of an exception during the API request. In the subsequent execution of the workflow, the system will retrieve the latest saved file from MinIO. It will then extract the last `siren` in the file, allowing the workflow to resume from that point onwards.
This approach serves as a resilient strategy, safeguarding against potential data loss caused by API disruptions. By storing partial data in MinIO, we ensure …

[data_pipelines][rne] Save flux json file even if it's not completed

---

data_pipelines/rne/flux/DAG.py

Running DAG at midnight instead of at 2am allows for an extra 2 hours of processing while RNE API has low traffic.

[DATA-PIPELINES][RNE]feat: run dag daily at midnight

---

data_pipelines/rne/flux/flux_tasks.py

With the latest update to RNE flux, we save all retrieved data from API even unfinished. This causes a formatting problem with the JSON object at the end of each file. The purpose of this PR is to resolve this issue. It accomplishes this by extracting the last correctly formatted JSON object from the file, obtaining the last SIREN from that object, and subsequently deleting the ill-formatted JSON object.
PS: It's important to note that these changes must be made within the context of the `database DAG`, which utilizes these files to generate an RNE database.

[DATA-PIPELINES][RNE]fix: get last siren from unfinished json 

---

DAG-insert-elk-sirene.py
config.py
data_preprocessing/ess_france.py
elasticsearch/data_enrichment.py
elasticsearch/mapping_index.py
elasticsearch/process_unites_legales.py
sqlite/queries/create_table_ess_france.py
sqlite/queries/select_fields_to_index.py
task_functions/create_additional_data_tables.py

closes #215
The `est_ess` field in the index was initially constructed using data from the `economie_sociale_solidaire_unite_legale` field in the SIRENE dataset. However, the updated ESS France dataset will now serve as an additional source for building this particular field.
Henceforth, `est_ess = est_ess_france || economie_sociale_solidaire_unite_legale`.

[DATA][ESS]feat: use new ESS France dataset to build `est_ess` field

---

config.py
data_pipelines/metadata/cc/DAG-get-metadata-cc.py
data_pipelines/metadata/cc/task_functions.py

closes https://github.com/etalab/annuaire-entreprises-search-infra/issues/218
Here's a summary of the changes introduced by the PR:
* Retrieves a list of "conventions collectives" from Dares, as detailed in the linked issue for further clarification.
* Retrieves the Kali list from the data.gouv source.
* Combines and merges these lists, giving priority to the Dares file as the primary source.
* The primary use of the combined list is in the Dares dataset, supplemented with additional information from the Kali dataset.
* The resulting JSON file is saved to MinIO and is utilized by the API metadata endpoint.
In essence, this PR enhances the Dares dataset by incorporating information from the Kali dataset, creating a comprehensive list that serves as a valuable resource for the API metadata …

[METADATA]feat: create json file with `conventions collectives` metadata

---

data_pipelines/rne/flux/DAG.py

The Flux DAG has been in execution for over 72 hours on the file dated October 31, 2023, and its size has surpassed 30 Gb. Unfortunately, the current timeout of 100 hours is proving insufficient, and there is no clear indication of when the process will conclude. Hopefully a 30 days timeout will be enough, though I doubt it 🤷‍♀️

[DATA-PIPELINES–[RNE]feat: increase timeout to 30 days for DAG RNE flux

---

elasticsearch/indexing_unite_legale.py

To enable the use of the `page_etablissements` parameter for all Sirens, including those with less than 100 establishments, a numerical extension has been incorporated into the document ID within Elasticsearch`siren-100`. This extension facilitates the application of the same logic in the API for filtering and querying documents by Siren, ensuring comprehensive coverage for Sirens with varying numbers of establishments.
Related to https://github.com/etalab/annuaire-entreprises-search-api/pull/317 and https://github.com/etalab/annuaire-entreprises-search-api/pull/320

[INDEX MAPPING]feat: add etabs number to doc id in elasticsearch

---

data_pipelines/rne/flux/flux_tasks.py

This pull request addresses the issue of an error being raised when there is no flux file present in MinIO. The proposed solution involves using a `None` value for the `last_siren` in such cases.

[DATA-PIPELINES][RNE]feat: return None if json last flux file doesn't exist

---

data_pipelines/rne/database/process_rne.py
data_pipelines/rne/database/rne_model.py
data_pipelines/rne/database/task_functions.py

Previously, there was ambiguity regarding the location of the `dirigeants` data returned by the RNE API. Typically, it was found within the `pouvoirs` block under the `exploitation` block. However, it has been discovered that for other types of `entreprises`, the `dirigeants` data may be included in different blocks.
Previously, our extraction process focused solely on retrieving the `pouvoirs` block for the `exploitation` type. In this pull request, we are expanding the extraction to include the `pouvoirs` block for the `personneMorale` type and the `identite` block for type `personnePhysique`.
This PR introduces a `RNECompany` data model designed to streamline the extraction of `dirigeant` data from JSON objects.
depends on https://github.com/etalab/annuaire-entreprises-search-infra/pull …

[DATA-PIPELINES][RNE]fix: extract `dirigeants` for all types of `entreprise`

---

maintenance/DAG_clean_logs.py

closes #231 
The [problem](https://stackoverflow.com/questions/73652663/airflow-dag-run-marked-as-success-although-the-tasks-didnt-run#:~:text=If%20you%20see%20dag%20runs,dates.) arises from the conflicting definitions of the `start_date`, which is set in both the `default_args` dictionary and the `DAG()` object with different values. Although DAG runs were marked as successful, the tasks failed to execute automatically unless manually triggered.
This pull request (PR) addresses the issue by removing the dynamic start date from the `default_args` dictionary and updating the `start_date` and `schedule_interval` parameters in the `DAG()` object. These changes aim to prevent the unintentional deletion of logs while other pipelines are executing.

[BUG][MAINTENANCE] fix: DAG to clean Airflow logs

---

helpers/minio_helpers.py
maintenance/DAG_clean_minio.py

This PR adds a DAG which deletes outdated RNE and SIRENE databases from MinIO if they are older than 3 days, while retaining a specified number of the most recent files(2 to 3 files).

[MAINTENANCE] feat: add workflow to delete old MinIO files periodically

---

workflows/data_pipelines/metadata/cc/DAG-get-metadata-cc.py

Schedule the `conventions collectives` DAG to run on the 2nd day of each month instead of a daily frequency, as the data is updated monthly.

[DATA-PIPELINES]chore: run cc dag only once a month

---

helpers/minio_helpers.py
helpers/update_color_file.py
workflows/data_pipelines/elasticsearch/task_functions/fetch_db.py
workflows/data_pipelines/elasticsearch/task_functions/sitemap.py
workflows/data_pipelines/etl/DAG_extract_transform_load.py
workflows/data_pipelines/etl/data_fetch_clean/etablissements.py
workflows/data_pipelines/etl/data_fetch_clean/unite_legale.py
workflows/data_pipelines/etl/task_functions/upload_db.py
workflows/data_pipelines/metadata/cc/task_functions.py
workflows/data_pipelines/rne/database/task_functions.py
workflows/data_pipelines/rne/flux/flux_tasks.py
workflows/data_pipelines/rne/stock/task_functions.py
workflows/maintenance/DAG_clean_minio.py

Depends on https://github.com/etalab/annuaire-entreprises-infrastructure/pull/37
This PR introduces a `MinioClient` class to encapsulate MinIO file upload and download operations. 
Some notable changes include the utilisation of the `MinioClient` class method to handle the upload of the `colour file`. This modification has also changed the `color_url` in MinIO to be now be inside the `env` specific folder(see https://github.com/etalab/annuaire-entreprises-infrastructure/pull/37).
Additionally, the client is now employed for storing the sitemap. It's important to note that the URL for the sitemap has not been changed like the colour URL,  since the website relies on it. Any alterations in this regard should be coordinated with the website to ensure consistency. 
Certain methods within the …

[REFACTOR]feat: add MinIOClient class

---

config.py
helpers/utils.py
workflows/data_pipelines/sirene/flux/DAG.py
workflows/data_pipelines/sirene/flux/task_functions.py

This PR involves relocating the workflows responsible for retrieving daily sirene flux data, including `unites légales`, `établissements`, and `non-diffusibles`, from the data.gouv pipelines to the core infrastructure. The collected data is subsequently stored in MinIO for further processing.
⚠️ PS: there is a [planned adjustment](https://github.com/etalab/annuaire-entreprises-search-infra/issues/241) to the path used in the preprocessing workflow starting Monday. This change will be implemented once the non-diffusible stock has been successfully recovered, ensuring a smooth transition in the data processing pipeline.

[DATA-PIPELINES]feat: get daily flux SIRENE

---

workflows/data_pipelines/rne/flux/rne_api.py

The RNE API has been experiencing difficulties in consistently providing comprehensive responses. To address this issue, this PR aims to mitigate the problem by reducing the page size. This adjustment is intended to lower the response size.

[DATA-PIPELINES][RNE]fix: lower rne flux page size

---

helpers/minio_helpers.py
workflows/data_pipelines/etl/data_fetch_clean/etablissements.py
workflows/data_pipelines/etl/data_fetch_clean/unite_legale.py

closes #241 
This PR involves transferring the Sirene flux path from the data.gouv infrastructure to the core infrastructure path. The files used will now be downloaded from the same bucket as the rest of the data utilised in our ETL process.

[DATA-PIPELINES]chore: update path source sirene flux

---

workflows/data_pipelines/elasticsearch/task_functions/sitemap.py

This PR makes changes to the sitemap to use the database stored in the ELK path instead of ETL path.

[FIX]Update sirene db path for sitemap creation

---

workflows/data_pipelines/etl/sqlite/helpers.py
workflows/data_pipelines/etl/sqlite/queries/colter.py
workflows/data_pipelines/etl/task_functions/create_additional_data_tables.py
workflows/data_pipelines/etl/task_functions/create_etablissements_tables.py
workflows/data_pipelines/etl/task_functions/create_unite_legale_tables.py

This PR aims to address the indexing failure of [METROPOLE DU GRAND PARIS (MGP)](https://annuaire-entreprises.data.gouv.fr/entreprise/200054781) in Elasticsearch, which occurs because it exceeds the allowed number of nested documents (20000). This issue arises primarily from numerous duplicates for each `elu`. 
The proposed solution in this PR is to remove these duplicates before indexing, rather than solely handling them on the API side.

[DATA-PIPELINES][FIX]Remove duplicates from `elus` table

---

workflows/data_pipelines/elasticsearch/mapping_index.py
workflows/data_pipelines/elasticsearch/sqlite/fields_to_index.py
workflows/data_pipelines/etl/data_fetch_clean/convention_collective.py
workflows/data_pipelines/etl/sqlite/helpers.py
workflows/data_pipelines/etl/sqlite/queries/convention_collective.py
workflows/data_pipelines/etl/task_functions/create_additional_data_tables.py

This pull PR a new field called 'liste_idcc' to the 'unite_legale' index in Elasticsearch. For each SIREN :
```
liste_idcc = {
[IDCC_A]: [siret1, siret2],
[IDCC_B]: [siret3, siret4],
}
```
The 'liste_idcc' field is indexed as a string in Elasticsearch to prevent excessive nesting of objects per document.

[INDEXING]Add `list_idcc` field to `unite legale` object

---

config.py
workflows/data_pipelines/elasticsearch/mapping_index.py
workflows/data_pipelines/elasticsearch/process_unites_legales.py
workflows/data_pipelines/elasticsearch/sqlite/fields_to_index.py
workflows/data_pipelines/etl/DAG_extract_transform_load.py
workflows/data_pipelines/etl/data_fetch_clean/marche_inclusion.py
workflows/data_pipelines/etl/sqlite/queries/marche_inclusion.py
workflows/data_pipelines/etl/task_functions/create_additional_data_tables.py
workflows/data_pipelines/marche_inclusion/DAG.py
workflows/data_pipelines/marche_inclusion/task_functions.py

Related to https://github.com/etalab/annuaire-entreprises-search-api/issues/304.
The changes implemented in this PR :
1. Creation of a daily DAG that interacts with the `Marché de l'Inclusion` API, retrieving information about all structures and storing them in a CSV file within MinIO.
2. Processing this retrieved data in the daily ETL workflow.
3. Indexing the processed data in Elasticsearch.
4. Addition of two fields, "est_siae" and "type_siae", at the SIREN level in Elasticsearch.
Before deploying this to production, there is a task pending:

[NEW DATA][MARCHE INCLUSION]Add marche inclusion data to index

---

workflows/data_pipelines/elasticsearch/DAG_index_data.py
workflows/data_pipelines/elasticsearch/DAG_snapshot_data.py
workflows/data_pipelines/etl/DAG_extract_transform_load.py
workflows/data_pipelines/marche_inclusion/DAG.py
workflows/data_pipelines/rne/database/DAG.py
workflows/data_pipelines/rne/flux/DAG.py
workflows/data_pipelines/rne/stock/DAG.py
workflows/data_pipelines/sirene/flux/DAG.py
workflows/maintenance/DAG_clean_logs_and_runs.py
workflows/maintenance/DAG_clean_minio.py
workflows/maintenance/DAG_flush_and_execute_queries.py
workflows/maintenance/DAG_flush_cache_only.py
workflows/maintenance/DAG_restart_api.py

In this pull request, I've retained email notifications for failure scenarios, but I propose disabling notifications for successful executions of all DAGs except the main one. The main DAG will still trigger a Tchap notification update regardless of success or failure.

[CHORE]Decrease emailing about DAG status updates and notifications

---

workflows/data_pipelines/etl/data_fetch_clean/collectivite_territoriale.py

closes #310 
This PR addresses issues resulting from recent updates to the `elus` files on _data.gouv,_ which caused failures in the ETL process. Here's a breakdown of the changes:
1. Added a delimiter to the pandas DataFrame: In some columns, commas were present, which caused confusion for the parser. By specifying a delimiter, the parser can properly distinguish between values and avoid errors.
2. Replaced single quotation marks with apostrophes: Certain column names contained single quotation marks instead of apostrophes. This inconsistency led to a bug during the column renaming process. By replacing the single quotation marks with apostrophes, the column names are standardized and the bug is resolved.

[BUG][DATA-PIPELINES]Fix `elus` data processing

---

workflows/data_pipelines/rne/database/DAG.py

Extend the timeout period since the staging server's performance is lower compared to production.

[DATA-PIPELINES][RNE]chore: increase RNE database dag timeout to 8 days

---

tests/e2e_tests/response_tester.py
tests/e2e_tests/test_api.py
workflows/data_pipelines/etl/data_fetch_clean/convention_collective.py
workflows/data_pipelines/etl/data_fetch_clean/egapro.py
workflows/data_pipelines/etl/data_fetch_clean/entrepreneur_spectacle.py
workflows/data_pipelines/etl/data_fetch_clean/ess_france.py
workflows/data_pipelines/etl/data_fetch_clean/finess.py
workflows/data_pipelines/etl/data_fetch_clean/organisme_formation.py
workflows/data_pipelines/etl/data_fetch_clean/rge.py

The bug originated in the `Organisme de formation` data, which includes a boolean column with `True` or `False` values. When the CSV file is imported, all columns are initially cast as strings. I added a line of code to cast the `est_qualiopi` column as a boolean, but this resulted in the entire column being set to `True`. Consequently, all `organisme de formation` entries have been incorrectly labeled as `qualiopi` for the past two weeks.
The same boolean casting code was applied to other data sources, but it did not cause any critical issues since those columns already contained only `True` values. This pull request removes the boolean casting line from those data sources for consistency.

[BUG][ETL]fix: remove bool cast for bool fields

---

workflows/data_pipelines/rne/database/DAG.py
workflows/data_pipelines/rne/database/process_rne.py
workflows/data_pipelines/rne/database/task_functions.py

closes #336 
The previous strategy involved deleting records with the same SIREN but different JSON files, based on the assumption that the API only returns a SIREN once a day. However, it has been discovered that one JSON RNE file (a flux from one day) can contain the same records multiple times, sometimes up to ten times. This redundancy has caused the database size to become unmanageably large.
This PR addresses the issue by removing exact duplicates (same SIREN, same source file, same data) from the RNE database after all processing is complete, just before the database is uploaded to MinIO. Testing in dev environment showed a significant reduction in database file size from **170 GB to 36 GB, an 80% decrease**. This optimisation also results in considerable time savings for zipping, …

[RNE][OPTIMISATION]Remove duplicates from rne db before uploading to MinIO

---

workflows/data_pipelines/agence_bio/task_functions.py
workflows/data_pipelines/sirene/flux/DAG.py
workflows/data_pipelines/sirene/flux/task_functions.py

This PR includes the following updates:
- **Enhanced Error Handling**: Implements handling for HTTP 429 errors (rate limiting) from the Sirene API. It includes a retry mechanism with a delay to manage rate limits effectively. Same for API Bio.
- **Notification Improvements**: Adds functionality to send notifications to Tchap in the event of a failure in the Sirene flux workflow. Additionally, it introduces an email variable that was previously omitted in the settings, which resolves issues with missing email notifications for failed workflows.

[FIX][DATA-PIPELINES]Handle http errors in API calls

---

workflows/data_pipelines/sirene/flux/DAG.py

This PR halts the execution of Flux Sirene on the first day of each month to prevent errors caused by the recently published stock data.

[INSEE]chore: block flux sirene execution on the 1st of every month

---

workflows/data_pipelines/etl/DAG_extract_transform_load.py

Due to API instabilities (slower response) caused by the snapshot import around 15:30, this PR reschedules the ETL from 5:00 AM to 9:00 AM. The ETL process takes approximately 3 hours, and indexing requires about 7 hours, which shifts the snapshot workflow trigger to around 19:00. This is a temporary solution until the root cause of the issue is identified.

[FIX]Reschedule ETL for later in the morning

---

helpers/tchap.py
workflows/data_pipelines/agence_bio/DAG.py

Previously, notifications were only sent via email. This PR introduces a Tchap notification to ensure the information is shared more effectively.

[CHORE]Add Tchap failure notifications to agence bio workflow

---

workflows/data_pipelines/etl/DAG_extract_transform_load.py
workflows/data_pipelines/etl/data_fetch_clean/etablissements.py
workflows/data_pipelines/etl/data_fetch_clean/unite_legale.py

At the start of each month, a new Sirene stock file is usually published on data.gouv on the 1st. When querying the Sirene API for the differential between the last day of the previous month and the first day of the new month, an error occurs. This API error results in the absence of the new flux files on MinIO between the last day of the month and the 2nd of the new month. Consequently, this causes an issue when trying to create the flux tables (ul, etab, and siege).
This PR resolves the issue by skipping the task of filling (but still creating) flux tables if the new month's flux files are not yet found on MinIO. It ensures that the subsequent tasks can execute smoothly, even if the files are missing during this transition period.

[BUG]Skip flow sirene in the beginning of the month

---

workflows/data_pipelines/rne/flux/rne_api.py

It appears that the SIREN associated that comes after `357802032` for October 10th is "La Poste." As a temporary solution to move things forward, the issue is caused by "La Poste" being too large to render.
This is a temp fix for the 10th of October only.

[TMP][RNE]fix: skip la poste when siren before is a certain value

---

helpers/minio_helpers.py

In two log statements, the arguments passed for formatting do not match the placeholders in the log message string. 
It causes a lot of warnings in Airflow logs. Using f-string instead.

[LOGS]fix: remove string substitution in logs

---

workflows/data_pipelines/etl/DAG_extract_transform_load.py

Indexing should end later in the evening to avoid latency on Elasticsearch.

[PERFORMANCE]chore: delay etl dag by one hour

---

workflows/data_pipelines/bilans_financiers/task_functions.py

With the update from Pandas 1.5 to 2.2, the handling of datetime objects has changed. Pandas now uses the `pandas.Timestamp` type, which is based on the Arrow-backed PyArrow library instead of NumPy. This shift has introduced changes in parsing behavior, leading to unexpected results in certain cases.

fix: update datetime usage in pandas

---

workflows/data_pipelines/bilans_financiers/task_functions.py

This PR addresses an issue encountered when reading the CSV file bilans_entreprises.csv in the process_bilans_financiers function. The original implementation resulted in a ValueError due to a mismatch between the expected column names and the actual column names in the CSV file, which was caused by the presence of a Byte Order Mark (BOM) at the beginning of the file.
Changes Made:
Updated  function to use the encoding='utf-8-sig' parameter. This change ensures that any BOM present in the CSV file is automatically detected and removed, allowing for proper reading of the file without causing errors related to column name mismatch.

[BILANS-FINANCIERS]fix: handle BOM in csv file by using utf-8-sig encoding

---

helpers/data_processor.py

Make sure the task built on top of `DataProcessor.download_data()` are failing when the download fails.

[BUG] Fix task status of DataProcessor.download_data()

---

README.md
workflows/data_pipelines/agence_bio/README.md
workflows/data_pipelines/bilans_financiers/README.md
workflows/data_pipelines/colter/README.md
workflows/data_pipelines/convcollective/README.md
workflows/data_pipelines/egapro/README.md
workflows/data_pipelines/ess_france/README.md
workflows/data_pipelines/finess/README.md
workflows/data_pipelines/formation/README.md
workflows/data_pipelines/marche_inclusion/README.md
workflows/data_pipelines/rge/README.md
workflows/data_pipelines/rne/flux/README.md
workflows/data_pipelines/rne/stock/README.md
workflows/data_pipelines/sirene/flux/README.md
workflows/data_pipelines/sirene/stock/README.md
workflows/data_pipelines/spectacle/README.md
workflows/data_pipelines/uai/README.md

Update of the project READMEs.

[DOCS] Update and harmonise README files

---

workflows/data_pipelines/sirene/flux/dag.py

This PR addresses the recurring zombie task error encountered when processing large `etablissements` data from Insee in the `get_flux_etablissements` task. The issue arises due to the size of the dataset causing the task to exceed heartbeat or timeout thresholds, leaving it in an inconsistent state.

[SIRENE][FLUX]fix: increase dag timeout

---

helpers/api_client.py
workflows/data_pipelines/sirene/flux/api.py
workflows/data_pipelines/sirene/flux/processor.py

related to https://github.com/annuaire-entreprises-data-gouv-fr/search-infra/pull/462
This PR addresses the recurring zombie task error encountered when processing large etablissements data from Insee in the get_flux_etablissements task. The issue arises due to the size of the list when converted to a pandas df.

[BUG]fix(sirene): save flux data in chunks to avoid memory issues

---

tests/e2e_tests/test_api.py

Indexing workflow fail because `societe generale` is no longer `organisme formation`.

[BUG]fix: update e2e test in indexing workflow

---

helpers/data_processor.py
helpers/utils.py
workflows/data_pipelines/agence_bio/processor.py
workflows/data_pipelines/bilans_financiers/processor.py
workflows/data_pipelines/convcollective/processor.py
workflows/data_pipelines/egapro/processor.py
workflows/data_pipelines/ess_france/processor.py
workflows/data_pipelines/finess/processor.py
workflows/data_pipelines/formation/processor.py
workflows/data_pipelines/marche_inclusion/processor.py
workflows/data_pipelines/rge/processor.py
workflows/data_pipelines/sirene/flux/api.py
workflows/data_pipelines/sirene/flux/processor.py
workflows/data_pipelines/spectacle/processor.py
workflows/data_pipelines/uai/processor.py

The Sirene API is doing a lot of API calls. 
Our current code can't scale enough so the tasks are failing due to too much RAM usage.
This PR proposes a fix so we only save in the RAM one day of updates at a time instead of all the days since the begining of the month.
The `DataProcessor.push_unique_count()` has been refactored to `DataProcessor.push_message()` to allow sending messages without having the whole column to count still in memory.

[BUG] Fix get flux etablissements RAM usage issue

---

helpers/utils.py
workflows/data_pipelines/sirene/flux/processor.py

✅ Ran successfully on dev-01.
> Il faut garder que la dernière version d'un row dans le retour de l'API
par exemple si siret_X a changé le 01-02-2025 et le 15-02-2025 dans ton code t'auras les deux lignes dans le csv
alors que que quand on appelait par mois, si par défaut la dernière mise à jour qui est incluse dans la réponse
c'est un peu comme ce que je fais dans le RNE, il faut écraser les anciennes mises à jour.
😄

[BUG][SIRENE.FLUX] Handle siren.t with multiple updates

---

workflows/data_pipelines/elasticsearch/task_functions/sitemap.py

Make AIRFLOW_ENV value differentiate dev-01 with dev-02 so they won't conflict on MinIO.
Related to.. https://github.com/annuaire-entreprises-data-gouv-fr/infrastructure/pull/385
We would end up with:
`dev` would be the default. It can happen while running a DAG in local.
```python
AIRFLOW_ENV = Variable.get("ENV", "dev")
```

Prepare MinIO to accept dev-02 or dev-01 as new AIRFLOW_ENV variable

---

workflows/data_pipelines/sirene/flux/config.py

The metadata.json file from the Sirene flux was missing.

[BUG][ETL][FLUX.SIRENE] minio path

---

workflows/data_pipelines/elasticsearch/DAG_snapshot_data.py

If indexing succeeds after a retry in the snapshot workflow, we are not notified.

[Notifications]chore: send Mattermost failure notif if snapshot fail

---

tests/e2e_tests/test_api.py
workflows/data_pipelines/alim_confiance/README.md
workflows/data_pipelines/alim_confiance/config.py
workflows/data_pipelines/alim_confiance/dag.py
workflows/data_pipelines/alim_confiance/processor.py
workflows/data_pipelines/data_gouv/processor.py
workflows/data_pipelines/data_gouv/queries.py
workflows/data_pipelines/elasticsearch/mapping_index.py
workflows/data_pipelines/elasticsearch/process_unites_legales.py
workflows/data_pipelines/elasticsearch/sqlite/fields_to_index.py
workflows/data_pipelines/etl/dag.py
workflows/data_pipelines/etl/task_functions/create_json_last_modified.py

Related to https://github.com/annuaire-entreprises-data-gouv-fr/search-api/issues/510
The dataset is not available at the moment on datagouv. The DAG should be activated only once it is available again.
In the meantime a locally created output has been uploaded to MinIO so the ETL DAG and API can already run as expected.

[ALIM'CONFIANCE] Add alim'confiance to ES index

---

workflows/data_pipelines/elasticsearch/task_functions/snapshot.py

Related to https://github.com/annuaire-entreprises-data-gouv-fr/search-infra/issues/503
It has been a bit painful to test but it seems that this simple fix is working. The failure was due to a default timeout set at 10s. Increasing it to 60s for that particular request did the trick.
Now:
```
[2025-05-18, 09:39:29 CEST] {snapshot.py:194} INFO - Deleting snapshot siren-20250512074927 from data-staging
[2025-05-18, 09:39:44 CEST] {base.py:265} INFO - DELETE https://elastic.staging.recherche-entreprises.infra.api.gouv.fr:9200/_snapshot/data-staging/siren-20250512074927 [status:200 request:14.243s]
[2025-05-18, 09:39:44 CEST] {python.py:237} INFO - Done. Returned value was: None
```
Before:
```
[2025-05-19, 09:43:22 CEST] {base.py:288} WARNING - DELETE …
```

[BUG][ELASTIC SNAPSHOT] Fix timeout issue

---

workflows/data_pipelines/etl/sqlite/queries/unite_legale.py

related to https://github.com/annuaire-entreprises-data-gouv-fr/site/issues/1767
The SIREN 000.000.000 is currently displayed as non-diffusible on the website because we have been using the RNE data to determine the statut when the Sirene data is missing. However, since this appears to be an error on the Inpi side, we will now rely exclusively on the Sirene data for this field, whenever it is available.

[RNE]fix: don't use statut diffusion insee from rne
